### ISSUE TITLE
Failed to connect to peripheral 

### ISSUE THREAD

**Issue by dr-boss** [bendikwa/igrill#20] opened 2020-05-08 01:37 UTC
I checked the MAC of iGrill, is ok
the type is ok
all components are installed
but I receive error Failed to connect to peripheral.
The igrill work without problems with my android phone.
Can you help me?

`2020-05-08 03:31:56,072 MainThread DEBUG: Validating dict {'topic': 'grill/', 'interval': 20, 'type': 'igrill_v2', 'name': 'grill', 'address': 'D4:81:CA:23:3D:25'} with specs: {'list_type': <type 'dict'>, 'optional_entries': {'publish_missing_probes': <type 'bool'>, 'missing_probe_value': <type 'str'>}, 'required_entries': {'topic': <type 'str'>, 'interval': <type 'int'>, 'type': <type 'str'>, 'name': <type 'str'>, 'address': <type 'str'>}}

2020-05-08 03:31:56,075 grill DEBUG: Device thread grill (re)started, trying to connect to iGrill with address: D4:81:CA:23:3D:25

2020-05-08 03:31:56,075 grill DEBUG: Created new device with name grill

2020-05-08 03:31:56,076 grill DEBUG: Trying to connect to the device with address D4:81:CA:23:3D:25

2020-05-08 03:31:56,076 grill DEBUG: Calling btle.Peripheral.__init__ with lock: 3067462912

2020-05-08 03:31:56,086 grill DEBUG: Failed to connect to peripheral D4:81:CA:23:3D:25, addr type: public

2020-05-08 03:31:56,087 grill DEBUG: Sleeping for 20 seconds before retrying

2020-05-08 03:32:16,107 grill DEBUG: Device thread grill (re)started, trying to connect to iGrill with address: D4:81:CA:23:3D:25
2020-05-08 03:32:16,107 grill DEBUG: Created new device with name grill
2020-05-08 03:32:16,108 grill DEBUG: Trying to connect to the device with address D4:81:CA:23:3D:25
2020-05-08 03:32:16,108 grill DEBUG: Calling btle.Peripheral.__init__ with lock: 3067462912
2020-05-08 03:32:16,119 grill DEBUG: Failed to connect to peripheral D4:81:CA:23:3D:25, addr type: public
2020-05-08 03:32:16,119 grill DEBUG: Sleeping for 20 seconds before retrying`

**Comment by bendikwa** [comment] 2020-05-08 06:09
```
2020-05-08 03:31:56,076 grill DEBUG: Calling btle.Peripheral.init with lock: 3067462912
2020-05-08 03:31:56,086 grill DEBUG: Failed to connect to peripheral D4:81:CA:23:3D:25, addr type: public
```
When I have had weird connection issues in the past, it has been resolved by doing a power cycle of the igrill.

I looks like it fails immediately after trying to connect. I can't reproduce it exactly here. The only time i get a similar output is if i try to add a device with a wrong type, and the script tries to read a bluetooth UUID that is not present, but then I manage to connect to the device on the first try, before getting a line in the DEBUG log saying: `'NoneType' object has no attribute 'read'`
(Subsequent attempts to read from the device fails like yours)

A few thing to try:
1. Remove the bluetooth pairing from any other devices.
2. Remove any pairing done on the raspberry pi:

```
pi@raspberrypi:~/src/igrill $ bluetoothctl
Agent registered
[bluetooth]# paired-devices
Device <MAC> iGrill_V2
[bluetooth]# remove <MAC>
[DEL] Device <MAC> iGrill_V2
Device has been removed
[bluetooth]#
```
Turn igrill off, and scan for it in bluetoothctl.

```
[bluetooth]# scan on
Discovery started
... Wait for the device to appear ...
[NEW] Device <MAC> iGrill_V2
[bluetooth]# scan off
[bluetooth]# pair <MAC>
´´´

3. try to run the `./monitor.py` script

-Bendik

**Comment by bendikwa** [comment] 2020-05-08 12:18
(turn the device on again before scanning of course)

**Comment by dr-boss** [comment] 2020-05-09 00:31
I have the same problem, work around 2 minutes after pair (in debug and mqtt temperature showed) but after this small success the program return to previous state:
`2020-05-09 02:24:28,780 iGrill_V2 DEBUG: Calling btle.Peripheral.__init__ with lock: 3067262208
2020-05-09 02:24:33,784 iGrill_V2 DEBUG: Releasing lock: 3067262208
2020-05-09 02:24:37,528 iGrill_V2 DEBUG: Device disconnected
2020-05-09 02:24:37,528 iGrill_V2 DEBUG: Sleeping for 10 seconds before retrying
2020-05-09 02:24:47,538 iGrill_V2 DEBUG: Device thread iGrill_V2 (re)started, trying to connect to iGrill with address: D4:81:CA:23:3D:25
2020-05-09 02:24:47,538 iGrill_V2 DEBUG: Created new device with name iGrill_V2
2020-05-09 02:24:47,538 iGrill_V2 DEBUG: Trying to connect to the device with address D4:81:CA:23:3D:25
2020-05-09 02:24:47,539 iGrill_V2 DEBUG: Calling btle.Peripheral.__init__ with lock: 3067262208
^C2020-05-09 02:24:58,860 MainThread INFO: Signaling all device threads to finish
2020-05-09 02:25:27,791 iGrill_V2 DEBUG: Failed to connect to peripheral D4:81:CA:23:3D:25, addr type: public`

in bluetoothctl ... connect on / off every 10 second (like time in config for check data by monitor.py)
and after pair (when work for short time the display of iGrill2 is turn off (when connected with phone they stay on).

**Comment by bendikwa** [comment] 2020-05-10 18:58
I don't know what Raspberry pi you are you are using, but if you can, I would test with cabled network. (I have heard of trouble using WIFI and Bluetooth at the same time on Raspberry pi 3)

I run a igrill_v3 and a igrill_mini on a raspberry pi3, and have not had any of these problems, and since I dont have the devices you are using, and to be honest, don't have a lot of experience doing Bluetooth device programming, it is hard for me to help. The next step for me would be to start digging into system logs on the PI to see if there are some clues there.

**Comment by mjhcdk** [comment] 2020-05-19 10:49
Hi,  

I also have similar problem connecting via bluetooth to my Igrill_v2 from my PI4/Ubuntu-19 platform. I am able to pair via the bluetoothctl task as explained above with some additional commands.  but when I start monitor.py I get the same bluetooth connect error.  Any suggestions how to troubleshoot and fix this.  See output below 

Regards
Michael 

```
ubuntu@ubuntu:~/igrill$ sudo bluetoothctl
Agent registered
[iGrill_V2-6E39]# paired-devices 
Device 70:91:8F:05:6E:39 iGrill_V2-6E39
[iGrill_V2-6E39]# info 70:91:8F:05:6E:39 
Device 70:91:8F:05:6E:39 (public)
	Name: iGrill_V2-6E39
	Alias: iGrill_V2-6E39
	Appearance: 0x0200
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Battery Service           (0000180f-0000-1000-8000-00805f9b34fb)
	UUID: Vendor specific           (64ac0000-4a4b-4b58-9f37-94d3c52ffdf7)
	UUID: Vendor specific           (a5c50000-f186-4bd6-97f2-7ebacba0d708)
[iGrill_V2-6E39]# 
2020-05-19 12:48:26,735 grill DEBUG: Device thread grill (re)started, trying to connect to iGrill with address: 70:91:8F:05:6E:39
2020-05-19 12:48:26,735 grill DEBUG: Created new device with name grill
2020-05-19 12:48:26,736 grill DEBUG: Trying to connect to the device with address 70:91:8F:05:6E:39
2020-05-19 12:48:26,736 grill DEBUG: Calling btle.Peripheral.__init__ with lock: 281473370229936
2020-05-19 12:48:26,755 grill DEBUG: Failed to connect to peripheral 70:91:8F:05:6E:39, addr type: public
2020-05-19 12:48:26,755 grill DEBUG: Sleeping for 20 seconds before retrying
2020-05-19 12:48:46,765 grill DEBUG: Device thread grill (re)started, trying to connect to iGrill with address: 70:91:8F:05:6E:39
2020-05-19 12:48:46,766 grill DEBUG: Created new device with name grill
2020-05-19 12:48:46,766 grill DEBUG: Trying to connect to the device with address 70:91:8F:05:6E:39
2020-05-19 12:48:46,766 grill DEBUG: Calling btle.Peripheral.__init__ with lock: 281473370229936
2020-05-19 12:48:46,781 grill DEBUG: Failed to connect to peripheral 70:91:8F:05:6E:39, addr type: public
2020-05-19 12:48:46,782 grill DEBUG: Sleeping for 20 seconds before retrying
` 
```

**Comment by bhartvigsen** [comment] 2020-08-07 21:18
Same issue here.

EDIT: Following step 2 in troubleshooting resolved my issue. RTFM :)

**Comment by bendikwa** [comment] 2020-10-18 08:10
If anybody still have issues with flaky bluetooth connections, I strongly suggest testing with cabled Ethernet or a separate usb WiFi dongle. Other than this, and the tips mentioned above, I have no more suggestions.
Sorry.

**Closed as completed by bendikwa** 2020-10-18 08:10 UTC
